import io
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

def build_excel_report(report_data: dict) -> bytes:
    wb = openpyxl.Workbook()
    
    # Define styles
    header_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    
    sub_fill = PatternFill(start_color="3B82F6", end_color="3B82F6", fill_type="solid")
    sub_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    
    title_font = Font(name="Calibri", size=16, bold=True, color="1E3A8A")
    meta_font = Font(name="Calibri", size=10, italic=True, color="475569")
    bold_font = Font(name="Calibri", size=11, bold=True)
    
    thin_border = Border(
        left=Side(style="thin", color="CBD5E1"),
        right=Side(style="thin", color="CBD5E1"),
        top=Side(style="thin", color="CBD5E1"),
        bottom=Side(style="thin", color="CBD5E1")
    )
    
    # ----------------------------------------------------
    # Sheet 1: Executive Summary & Metrics
    # ----------------------------------------------------
    ws1 = wb.active
    ws1.title = "Executive Summary"
    
    metrics = report_data.get("metrics", {})
    
    ws1.cell(row=1, column=1, value=metrics.get("report_title", "FLOOD RESCUE EXECUTIVE REPORT")).font = title_font
    ws1.cell(row=2, column=1, value=f"Generated on: {metrics.get('generated_at', '')} | Generated by: {metrics.get('generated_by', 'Admin')}").font = meta_font
    
    ws1.cell(row=4, column=1, value="Key Disaster Metric").fill = header_fill
    ws1.cell(row=4, column=1).font = header_font
    ws1.cell(row=4, column=2, value="Value / Count").fill = header_fill
    ws1.cell(row=4, column=2).font = header_font
    
    kpi_rows = [
        ("Total Flood Incidents", metrics.get("total_incidents", 0)),
        ("Active Incidents", metrics.get("active_incidents", 0)),
        ("Total Population Affected", metrics.get("total_affected_population", 0)),
        ("Total Rescued Persons", metrics.get("total_rescued_persons", 0)),
        ("Total Missing Persons", metrics.get("total_missing_persons", 0)),
        ("Total Traced Persons", metrics.get("total_traced_persons", 0)),
        ("Active Relief Shelters", metrics.get("total_shelters", 0)),
        ("Shelter Total Capacity", metrics.get("shelter_total_capacity", 0)),
        ("Shelter Total Occupancy", metrics.get("shelter_total_occupancy", 0)),
        ("Shelter Occupancy Rate (%)", f"{metrics.get('shelter_occupancy_percentage', 0)}%"),
        ("Critical Medical Cases", metrics.get("critical_medical_cases", 0)),
        ("Low Stock Resources", metrics.get("low_stock_resources_count", 0))
    ]
    
    r_idx = 5
    for label, val in kpi_rows:
        ws1.cell(row=r_idx, column=1, value=label).border = thin_border
        cell_v = ws1.cell(row=r_idx, column=2, value=val)
        cell_v.border = thin_border
        cell_v.font = bold_font
        r_idx += 1
        
    r_idx += 2
    ws1.cell(row=r_idx, column=1, value="Actionable Recommendations").fill = sub_fill
    ws1.cell(row=r_idx, column=1).font = sub_font
    ws1.merge_cells(start_row=r_idx, start_column=1, end_row=r_idx, end_column=2)
    r_idx += 1
    
    recs = report_data.get("recommendations", [])
    for rec in recs:
        ws1.cell(row=r_idx, column=1, value=f"• {rec}").border = thin_border
        ws1.merge_cells(start_row=r_idx, start_column=1, end_row=r_idx, end_column=2)
        r_idx += 1

    # ----------------------------------------------------
    # Sheet 2: Incident Summary
    # ----------------------------------------------------
    ws2 = wb.create_sheet(title="Incidents")
    inc_headers = ["ID", "Incident Name", "Type", "District", "Severity", "Status", "Water Level", "Population Affected", "Start Date"]
    
    for c_idx, h in enumerate(inc_headers, 1):
        cell = ws2.cell(row=1, column=c_idx, value=h)
        cell.fill = header_fill
        cell.font = header_font
        
    incidents = report_data.get("incident_summary", [])
    for r_i, inc in enumerate(incidents, 2):
        ws2.cell(row=r_i, column=1, value=inc.get("id")).border = thin_border
        ws2.cell(row=r_i, column=2, value=inc.get("name")).border = thin_border
        ws2.cell(row=r_i, column=3, value=inc.get("type")).border = thin_border
        ws2.cell(row=r_i, column=4, value=inc.get("district")).border = thin_border
        ws2.cell(row=r_i, column=5, value=inc.get("severity")).border = thin_border
        ws2.cell(row=r_i, column=6, value=inc.get("status")).border = thin_border
        ws2.cell(row=r_i, column=7, value=inc.get("water_level")).border = thin_border
        ws2.cell(row=r_i, column=8, value=inc.get("population_affected")).border = thin_border
        ws2.cell(row=r_i, column=9, value=inc.get("start_date")).border = thin_border

    # ----------------------------------------------------
    # Sheet 3: Shelters
    # ----------------------------------------------------
    ws3 = wb.create_sheet(title="Relief Shelters")
    shelter_headers = ["Shelter Name", "District", "Capacity", "Occupancy", "Occupancy %", "Status", "Contact Person"]
    
    for c_idx, h in enumerate(shelter_headers, 1):
        cell = ws3.cell(row=1, column=c_idx, value=h)
        cell.fill = header_fill
        cell.font = header_font
        
    shelters = report_data.get("shelter_summary", [])
    for r_i, s in enumerate(shelters, 2):
        ws3.cell(row=r_i, column=1, value=s.get("name")).border = thin_border
        ws3.cell(row=r_i, column=2, value=s.get("district")).border = thin_border
        ws3.cell(row=r_i, column=3, value=s.get("capacity")).border = thin_border
        ws3.cell(row=r_i, column=4, value=s.get("occupancy")).border = thin_border
        ws3.cell(row=r_i, column=5, value=s.get("occupancy_pct")).border = thin_border
        ws3.cell(row=r_i, column=6, value=s.get("status")).border = thin_border
        ws3.cell(row=r_i, column=7, value=s.get("contact")).border = thin_border

    # ----------------------------------------------------
    # Sheet 4: Resources
    # ----------------------------------------------------
    ws4 = wb.create_sheet(title="Resources Inventory")
    res_headers = ["Resource Name", "Category", "Unit", "Total Quantity", "Allocated", "Available", "Minimum Required", "Status"]
    
    for c_idx, h in enumerate(res_headers, 1):
        cell = ws4.cell(row=1, column=c_idx, value=h)
        cell.fill = header_fill
        cell.font = header_font
        
    resources = report_data.get("resource_summary", [])
    for r_i, res in enumerate(resources, 2):
        ws4.cell(row=r_i, column=1, value=res.get("name")).border = thin_border
        ws4.cell(row=r_i, column=2, value=res.get("category")).border = thin_border
        ws4.cell(row=r_i, column=3, value=res.get("unit")).border = thin_border
        ws4.cell(row=r_i, column=4, value=res.get("total")).border = thin_border
        ws4.cell(row=r_i, column=5, value=res.get("allocated")).border = thin_border
        ws4.cell(row=r_i, column=6, value=res.get("available")).border = thin_border
        ws4.cell(row=r_i, column=7, value=res.get("minimum_required")).border = thin_border
        st_cell = ws4.cell(row=r_i, column=8, value=res.get("status"))
        st_cell.border = thin_border
        if res.get("status") == "CRITICAL LOW":
            st_cell.font = Font(name="Calibri", size=11, bold=True, color="991B1B")

    # Auto-adjust column widths for all worksheets
    for sheet in wb.worksheets:
        for col in sheet.columns:
            max_len = 0
            col_letter = get_column_letter(col[0].column)
            for cell in col:
                val_str = str(cell.value or '')
                if val_str and len(val_str) > max_len:
                    max_len = len(val_str)
            sheet.column_dimensions[col_letter].width = max(max_len + 3, 12)

    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()