import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

def build_pdf_report(report_data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#1e3a8a'),
        alignment=1,
        spaceAfter=4
    )
    
    meta_style = ParagraphStyle(
        'DocMeta',
        parent=styles['Normal'],
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#475569'),
        alignment=1,
        spaceAfter=12
    )
    
    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=12,
        leading=15,
        textColor=colors.HexColor('#1e40af'),
        spaceBefore=10,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#1e293b')
    )
    
    rec_style = ParagraphStyle(
        'RecText',
        parent=styles['Normal'],
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#991b1b')
    )

    story = []
    
    metrics = report_data.get('metrics', {})
    
    # Title & Metadata
    story.append(Paragraph(metrics.get('report_title', 'FLOOD RESCUE EXECUTIVE REPORT'), title_style))
    story.append(Paragraph(f"Generated on: {metrics.get('generated_at', '')} | Generated by: {metrics.get('generated_by', 'Admin')} | Status: OFFICIAL DISASTER LOG", meta_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563eb'), spaceBefore=2, spaceAfter=10))
    
    # 1. Key Metrics Table
    story.append(Paragraph("1. Key Disaster Performance Metrics", section_style))
    
    pop_str = f"{metrics.get('total_affected_population', 0):,}"
    resc_str = f"{metrics.get('total_rescued_persons', 0):,}"
    pct_str = f"{metrics.get('shelter_occupancy_percentage', 0)}%"
    
    kpi_data = [
        [Paragraph("<b>Total Incidents</b>", body_style), str(metrics.get('total_incidents', 0)), Paragraph("<b>Active Incidents</b>", body_style), str(metrics.get('active_incidents', 0))],
        [Paragraph("<b>Affected Population</b>", body_style), pop_str, Paragraph("<b>Total Rescued Persons</b>", body_style), resc_str],
        [Paragraph("<b>Missing Persons</b>", body_style), str(metrics.get('total_missing_persons', 0)), Paragraph("<b>Relief Shelters Open</b>", body_style), f"{metrics.get('total_shelters', 0)} ({pct_str} Occ)"],
        [Paragraph("<b>Critical Medical Cases</b>", body_style), str(metrics.get('critical_medical_cases', 0)), Paragraph("<b>Low-Stock Resources</b>", body_style), str(metrics.get('low_stock_resources_count', 0))]
    ]
    
    kpi_table = Table(kpi_data, colWidths=[140, 110, 140, 150])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 10))
    
    # 2. Executive Action Recommendations
    recs = report_data.get('recommendations', [])
    if recs:
        story.append(Paragraph("2. Strategic Directives & Recommendations", section_style))
        rec_data = [[Paragraph(f"<b>•</b> {r}", rec_style)] for r in recs]
        rec_table = Table(rec_data, colWidths=[540])
        rec_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#fef2f2')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#fca5a5')),
            ('PADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(rec_table)
        story.append(Spacer(1, 10))

    # 3. Incident Summary Table
    incidents = report_data.get('incident_summary', [])
    if incidents:
        story.append(Paragraph("3. Flood Incident Summary", section_style))
        inc_headers = [Paragraph("<b>Incident Name</b>", body_style), Paragraph("<b>District</b>", body_style), Paragraph("<b>Severity</b>", body_style), Paragraph("<b>Status</b>", body_style), Paragraph("<b>Water Level</b>", body_style), Paragraph("<b>Affected Pop.</b>", body_style)]
        inc_rows = [inc_headers]
        for i in incidents:
            ipop = f"{i.get('population_affected', 0):,}"
            inc_rows.append([
                Paragraph(i.get('name', ''), body_style),
                i.get('district', ''),
                i.get('severity', ''),
                i.get('status', ''),
                i.get('water_level', ''),
                ipop
            ])
        inc_table = Table(inc_rows, colWidths=[150, 80, 70, 70, 70, 100])
        inc_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#e2e8f0')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('PADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(inc_table)
        story.append(Spacer(1, 10))
        
    # 4. Shelter Occupancy Table
    shelters = report_data.get('shelter_summary', [])
    if shelters:
        story.append(Paragraph("4. Relief Shelter Capacity & Occupancy Status", section_style))
        s_headers = [Paragraph("<b>Shelter Name</b>", body_style), Paragraph("<b>District</b>", body_style), Paragraph("<b>Capacity</b>", body_style), Paragraph("<b>Occupancy</b>", body_style), Paragraph("<b>Occupancy %</b>", body_style), Paragraph("<b>Status</b>", body_style)]
        s_rows = [s_headers]
        for s in shelters:
            s_rows.append([
                Paragraph(s.get('name', ''), body_style),
                s.get('district', ''),
                str(s.get('capacity', 0)),
                str(s.get('occupancy', 0)),
                s.get('occupancy_pct', ''),
                s.get('status', '')
            ])
        s_table = Table(s_rows, colWidths=[170, 80, 65, 65, 80, 80])
        s_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#e2e8f0')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('PADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(s_table)
        
    doc.build(story)
    return buffer.getvalue()
